name = "PooksoftOptionsKit"
uuid = "f44ba3c4-0ba4-432c-ac21-0a461a95f434"
authors = ["Jeffrey Varner <jvarner@pooksoft.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PooksoftBase = "17dff602-ea15-4a83-a4cd-e8c4e335a075"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "191fdcea-f9f2-43e0-b922-d33f71e2abc3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
